# Generated by Django 5.0.6 on 2024-06-19 23:13

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [ TrigramExtension() ]
